{
 "title": "Storage backend statistics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "2m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "instance",
    "query": "label_values(swh_storage_request_duration_seconds_bucket, instance)"
   },
   {
    "name": "endpoint",
    "query": "label_values(swh_storage_request_duration_seconds_bucket{instance=\"$instance\"}, endpoint)"
   },
   {
    "name": "role",
    "query": {
     "query": "label_values(swh_storage_request_duration_seconds_sum,role)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(swh_storage_request_duration_seconds_count{instance=\"$instance\", endpoint=\"$endpoint\", role=\"$role\"}[$interval])",
     "legendFormat": "number of req/s"
    },
    {
     "expr": "rate(swh_storage_request_duration_seconds_sum{instance=\"$instance\", endpoint=\"$endpoint\", role=\"$role\"}[$interval]) / rate(swh_storage_request_duration_seconds_count{instance=\"$instance\", endpoint=\"$endpoint\", role=\"$role\"}[$interval])",
     "legendFormat": "mean resp time"
    }
   ]
  },
  {
   "title": "Response time (25%-75%)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.25, rate(swh_storage_request_duration_seconds_bucket{instance=\"$instance\", endpoint=\"$endpoint\", role=\"$role\"}[$interval]))",
     "legendFormat": "0.25"
    },
    {
     "expr": "histogram_quantile(0.5, rate(swh_storage_request_duration_seconds_bucket{instance=\"$instance\", endpoint=\"$endpoint\", role=\"$role\"}[$interval]))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.75, rate(swh_storage_request_duration_seconds_bucket{instance=\"$instance\", endpoint=\"$endpoint\", role=\"$role\"}[$interval]))",
     "legendFormat": "0.75"
    },
    {
     "expr": "histogram_quantile(1.0, rate(swh_storage_request_duration_seconds_bucket{instance=\"$instance\", endpoint=\"$endpoint\", role=\"$role\"}[$interval]))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Response time distribution",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(swh_storage_request_duration_seconds_bucket{instance=\"$instance\",endpoint=\"$endpoint\", role=\"$role\"}[$interval])",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}