{
 "title": "Content Replayer Advanced",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "30s,1m,2m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "docker_host",
    "label": "Docker Host",
    "query": {
     "query": "label_values(swh_content_replayer_operations_total, hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "GET",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(le) (rate(swh_content_replayer_duration_seconds_bucket{request=\"get\", hostname=~\"$docker_host\"}[$interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "GET",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.25, sum by (le) (rate(swh_content_replayer_duration_seconds_bucket{request=\"get\", hostname=~\"$docker_host\"}[$interval])))",
     "legendFormat": "25%"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(swh_content_replayer_duration_seconds_bucket{request=\"get\", hostname=~\"$docker_host\"}[$interval])))",
     "legendFormat": "75%"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(swh_content_replayer_duration_seconds_bucket{request=\"get\", hostname=~\"$docker_host\"}[$interval])))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(swh_content_replayer_duration_seconds_bucket{request=\"get\", hostname=~\"$docker_host\"}[$interval])))",
     "legendFormat": "95%"
    }
   ]
  },
  {
   "title": "GET (99% by host)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, hostname) (rate(swh_content_replayer_duration_seconds_bucket{request=\"get\", hostname=~\"$docker_host\"}[$interval])))",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "PUT",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(le)(rate(swh_content_replayer_duration_seconds_bucket{request=\"put\", hostname=~\"$docker_host\"}[$interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "PUT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.25, sum by(le) (rate(swh_content_replayer_duration_seconds_bucket{request=\"put\", hostname=~\"$docker_host\"}[$interval])))",
     "legendFormat": "25%"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le)(rate(swh_content_replayer_duration_seconds_bucket{request=\"put\", hostname=~\"$docker_host\"}[$interval])))",
     "legendFormat": "75%"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le)(rate(swh_content_replayer_duration_seconds_bucket{request=\"put\", hostname=~\"$docker_host\"}[$interval])))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le)(rate(swh_content_replayer_duration_seconds_bucket{request=\"put\", hostname=~\"$docker_host\"}[$interval])))",
     "legendFormat": "95%"
    }
   ]
  },
  {
   "title": "PUT (99% by host)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, hostname)(rate(swh_content_replayer_duration_seconds_bucket{request=\"put\", hostname=~\"$docker_host\"}[$interval])))",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Number of blobs processed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by(decision)(rate(swh_content_replayer_operations_total{hostname=~\"$docker_host\"}[$interval]))",
     "legendFormat": "{{decision}}"
    }
   ]
  },
  {
   "title": "Number of blobs processed - copied by host",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by(hostname)(rate(swh_content_replayer_operations_total{decision=\"copied\", hostname=~\"$docker_host\"}[$interval]))",
     "legendFormat": "{{decision}}"
    }
   ]
  },
  {
   "title": "Consumer status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "sum (swh_journal_client_status{role=\"content-replayer\", hostname=~\"$docker_host\"})",
     "legendFormat": "total"
    },
    {
     "expr": "sum by(status) (swh_journal_client_status{role=\"content-replayer\", hostname=~\"$docker_host\"})",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Volume Processed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate(swh_content_replayer_bytes{hostname=~\"$docker_host\"}[$interval]))",
     "legendFormat": "Volume"
    }
   ]
  },
  {
   "title": "Volume Processed - copied by host",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by(hostname) (rate(swh_content_replayer_bytes{hostname=~\"$docker_host\"}[$interval]))",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Number of queries per backend",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by(backend,status)(rate(swh_objstorage_multiplexer_backend_total{endpoint=\"get\"}[$interval]))",
     "legendFormat": "{{backend}}: {{status}}"
    }
   ]
  },
  {
   "title": "S3",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by(le) (rate(swh_objstorage_request_duration_seconds_bucket{name=\"s3\",endpoint=\"get\"}[$interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Azure",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "targets": [
    {
     "expr": "sum by(le) (rate(swh_objstorage_request_duration_seconds_bucket{name=\"azure-prefixed\", endpoint=\"get\"}[$interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Rocquencourt",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "targets": [
    {
     "expr": "sum by(le) (rate(swh_objstorage_request_duration_seconds_bucket{endpoint=\"get\",name=\"remote\"}[$interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}