{
 "title": "Content Replayer",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "30s,1m,2m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "GET",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(swh_content_replayer_duration_seconds_bucket{request=\"get\", role=\"content-replayer\"}[$interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "PUT",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(swh_content_replayer_duration_seconds_bucket{request=\"put\",role=\"content-replayer\"}[$interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "IN",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.25, rate(swh_objstorage_request_duration_seconds_bucket{endpoint=\"__contains__\"}[$interval]))",
     "legendFormat": "25%"
    },
    {
     "expr": "histogram_quantile(0.75, rate(swh_objstorage_request_duration_seconds_bucket{endpoint=\"__contains__\"}[$interval]))",
     "legendFormat": "75%"
    },
    {
     "expr": "histogram_quantile(0.5, rate(swh_objstorage_request_duration_seconds_bucket{endpoint=\"__contains__\"}[$interval]))",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "GET",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.25, rate(swh_content_replayer_duration_seconds_bucket{request=\"get\",role=\"content-replayer\"}[$interval]))",
     "legendFormat": "25%"
    },
    {
     "expr": "histogram_quantile(0.75, rate(swh_content_replayer_duration_seconds_bucket{request=\"get\",role=\"content-replayer\"}[$interval]))",
     "legendFormat": "75%"
    },
    {
     "expr": "histogram_quantile(0.5, rate(swh_content_replayer_duration_seconds_bucket{request=\"get\",role=\"content-replayer\"}[$interval]))",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "PUT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.25, rate(swh_content_replayer_duration_seconds_bucket{request=\"put\",role=\"content-replayer\"}[$interval]))",
     "legendFormat": "25%"
    },
    {
     "expr": "histogram_quantile(0.75, rate(swh_content_replayer_duration_seconds_bucket{request=\"put\",role=\"content-replayer\"}[$interval]))",
     "legendFormat": "75%"
    },
    {
     "expr": "histogram_quantile(0.5, rate(swh_content_replayer_duration_seconds_bucket{request=\"put\",role=\"content-replayer\"}[$interval]))",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "Volume Processed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(swh_content_replayer_bytes{role=\"content-replayer\"}[$interval])",
     "legendFormat": "Volume"
    }
   ]
  },
  {
   "title": "Number of blobs processed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(swh_content_replayer_operations_total{role=\"content-replayer\"}[$interval])",
     "legendFormat": "{{decision}}"
    }
   ]
  },
  {
   "title": "Consumer status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "sum (swh_journal_client_status{role=\"content-replayer\"})",
     "legendFormat": "total"
    },
    {
     "expr": "sum by(status) (swh_journal_client_status{role=\"content-replayer\"})",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}