{
 "title": "Content Replayer",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Volume Processed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(swh_content_replayer_bytes[5m])",
     "legendFormat": "Volume"
    }
   ]
  },
  {
   "title": "Number of blobs processed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(swh_content_replayer_operations_total[5m])",
     "legendFormat": "Blobs"
    }
   ]
  },
  {
   "title": "Requests Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(swh_content_replayer_duration_seconds_sum[5m])",
     "legendFormat": "{{request}}"
    }
   ]
  }
 ]
}